# Generated by Django 2.1 on 2018-08-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
